"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { getSession } from "@/lib/session";
import { brl } from "@/lib/utils";
const empty:any={name:"",phone:"",email:"",source:"",stage:"novo",expected_value:0,notes:""};
export default function CrmPage(){
 const[session,setSession]=useState<any>(null);const[rows,setRows]=useState<any[]>([]);const[form,setForm]=useState<any>(empty);const[id,setId]=useState("");const[msg,setMsg]=useState("");
 useEffect(()=>{const s=getSession();if(!s){location.href="/login";return;}setSession(s);load(s.company_id)},[]);
 async function load(cid=session?.company_id){if(!cid)return;const{data}=await supabase.from("crm_leads").select("*").eq("company_id",cid).order("created_at",{ascending:false});setRows(data||[])}
 async function save(){if(!session||!form.name)return;const payload={...form,company_id:session.company_id,updated_at:new Date().toISOString()};const r=id?await supabase.from("crm_leads").update(payload).eq("id",id):await supabase.from("crm_leads").insert(payload);if(r.error)return setMsg(r.error.message);setMsg("Lead salvo.");setId("");setForm(empty);load()}
 return <div className="space-y-6"><h1 className="text-3xl font-black">CRM</h1><section className="card p-4 grid md:grid-cols-3 gap-3"><input placeholder="Nome" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Telefone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="Origem" value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/><select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})}><option value="novo">Novo</option><option value="contato">Contato</option><option value="proposta">Proposta</option><option value="ganho">Ganho</option><option value="perdido">Perdido</option></select><input type="number" placeholder="Valor previsto" value={form.expected_value} onChange={e=>setForm({...form,expected_value:e.target.value})}/><input placeholder="Notas" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button className="btn-primary" onClick={save}>{id?"Salvar":"Criar lead"}</button>{msg&&<p className="text-yellow-300">{msg}</p>}</section><section className="card p-4 overflow-x-auto"><table className="w-full"><thead><tr className="text-left text-zinc-400"><th>Lead</th><th>Telefone</th><th>Etapa</th><th>Valor</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} onClick={()=>{setId(r.id);setForm({...empty,...r})}} className="border-b border-zinc-800 cursor-pointer"><td className="p-2">{r.name}</td><td>{r.phone}</td><td>{r.stage}</td><td>{brl(r.expected_value)}</td></tr>)}</tbody></table></section></div>
}
