"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { getSession } from "@/lib/session";
const empty:any={name:"",document:"",whatsapp:"",email:"",address:"",manager_name:"",active:true};
export default function BranchesPage(){
 const[session,setSession]=useState<any>(null);const[rows,setRows]=useState<any[]>([]);const[form,setForm]=useState<any>(empty);const[id,setId]=useState("");const[msg,setMsg]=useState("");
 useEffect(()=>{const s=getSession();if(!s){location.href="/login";return;}if(!(s.master_admin||s.company_admin||s.role==="Administrador")){location.href="/dashboard";return;}setSession(s);load(s.company_id)},[]);
 async function load(cid=session?.company_id){if(!cid)return;const{data}=await supabase.from("company_branches").select("*").eq("company_id",cid).order("name");setRows(data||[])}
 async function save(){if(!session)return;if(!form.name)return setMsg("Informe o nome da loja/filial.");const payload={...form,company_id:session.company_id,updated_at:new Date().toISOString()};const r=id?await supabase.from("company_branches").update(payload).eq("id",id):await supabase.from("company_branches").insert(payload);if(r.error)return setMsg(r.error.message);setMsg("Salvo.");setId("");setForm(empty);load()}
 async function del(){if(!id)return setMsg("Selecione uma filial.");if(!confirm("Excluir filial?"))return;const{error}=await supabase.from("company_branches").delete().eq("id",id);if(error)return setMsg(error.message);setId("");setForm(empty);load()}
 return <div className="space-y-6"><h1 className="text-3xl font-black">Multi Loja / Filiais</h1><p className="text-zinc-400">Cadastre lojas/filiais e use em estoque, OS e financeiro.</p><section className="card p-4 grid md:grid-cols-3 gap-3"><input placeholder="Nome da loja" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="CNPJ/CPF" value={form.document} onChange={e=>setForm({...form,document:e.target.value})}/><input placeholder="WhatsApp" value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/><input placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="Endereço" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><input placeholder="Gerente" value={form.manager_name} onChange={e=>setForm({...form,manager_name:e.target.value})}/><label className="flex gap-2"><input type="checkbox" checked={!!form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Ativa</label><div className="flex gap-2 md:col-span-3"><button className="btn-primary" onClick={save}>{id?"Salvar":"Criar filial"}</button><button className="btn-danger" onClick={del}>Excluir</button><button className="btn-secondary" onClick={()=>{setId("");setForm(empty)}}>Limpar</button></div>{msg&&<p className="text-yellow-300 md:col-span-3">{msg}</p>}</section><section className="card p-4 overflow-x-auto"><table className="w-full"><thead><tr className="text-left text-zinc-400"><th>Loja</th><th>WhatsApp</th><th>Gerente</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} onClick={()=>{setId(r.id);setForm({...empty,...r})}} className="border-b border-zinc-800 cursor-pointer hover:bg-zinc-800"><td className="p-2">{r.name}</td><td>{r.whatsapp}</td><td>{r.manager_name}</td><td>{r.active?"Ativa":"Inativa"}</td></tr>)}</tbody></table></section></div>
}
