"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { getSession } from "@/lib/session";
import { paymentProviders } from "@/lib/payments";

const empty:any={provider:"manual",display_name:"",api_base_url:"",access_token:"",public_key:"",webhook_secret:"",pix_key:"",success_url:"",failure_url:"",notification_url:"",active:false,sandbox:true,instructions:""};

export default function PaymentSettingsPage(){
  const[session,setSession]=useState<any>(null);
  const[mode,setMode]=useState<"saas"|"company">("company");
  const[rows,setRows]=useState<any[]>([]);
  const[form,setForm]=useState<any>(empty);
  const[id,setId]=useState("");
  const[msg,setMsg]=useState("");
  useEffect(()=>{const s=getSession();if(!s){location.href="/login";return;}if(!(s.master_admin||s.company_admin||s.role==="Administrador")){location.href="/dashboard";return;}setSession(s);const m=s.master_admin?"saas":"company";setMode(m);load(s,m)},[]);
  async function load(s=session,m=mode){if(!s)return;const table=m==="saas"?"payment_gateways":"company_payment_settings";const cid=m==="saas"?"00000000-0000-0000-0000-000000000001":s.company_id;const{data,error}=await supabase.from(table).select("*").eq("company_id",cid).order("provider");if(error)setMsg(error.message);setRows(data||[])}
  function changeMode(m:"saas"|"company"){if(m==="saas"&&!session?.master_admin)return;setMode(m);setId("");setForm(empty);load(session,m)}
  async function save(){if(!session)return;const table=mode==="saas"?"payment_gateways":"company_payment_settings";const cid=mode==="saas"?"00000000-0000-0000-0000-000000000001":session.company_id;const payload:any={...form,company_id:cid,updated_at:new Date().toISOString()};if(mode==="saas")payload.gateway_scope="saas";const r=id?await supabase.from(table).update(payload).eq("id",id):await supabase.from(table).insert(payload);if(r.error)return setMsg(r.error.message);setMsg("Configuração salva.");setId("");setForm(empty);load(session,mode)}
  async function remove(){if(!id)return setMsg("Selecione uma configuração.");if(!confirm("Excluir configuração?"))return;const table=mode==="saas"?"payment_gateways":"company_payment_settings";const{error}=await supabase.from(table).delete().eq("id",id);if(error)return setMsg(error.message);setMsg("Configuração excluída.");setId("");setForm(empty);load(session,mode)}
  const webhook=typeof window!=="undefined"?`${window.location.origin}/api/payments/webhook`:"/api/payments/webhook";
  return <div className="space-y-6"><h1 className="text-3xl font-black">Pagamentos / Keys</h1><p className="text-zinc-400">Master configura recebimento dos planos SaaS. Administrador da empresa configura recebimento da própria loja.</p>
    <section className="card p-4 flex flex-wrap gap-2">{session?.master_admin&&<button className={mode==="saas"?"btn-primary":"btn-secondary"} onClick={()=>changeMode("saas")}>Planos SaaS / Dono</button>}<button className={mode==="company"?"btn-primary":"btn-secondary"} onClick={()=>changeMode("company")}>Recebimentos da Empresa</button></section>
    <section className="card p-4 text-sm text-zinc-300"><b>Webhook:</b> {webhook}<p className="text-zinc-400 mt-1">Use esse link no Mercado Pago, Asaas, Stripe ou outro gateway.</p></section>
    <section className="card p-4 grid md:grid-cols-3 gap-3"><select value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})}>{paymentProviders.map(p=><option key={p.value} value={p.value}>{p.label}</option>)}</select><input placeholder="Nome exibido" value={form.display_name||""} onChange={e=>setForm({...form,display_name:e.target.value})}/><input placeholder="URL/API ou link externo" value={form.api_base_url||""} onChange={e=>setForm({...form,api_base_url:e.target.value})}/><input placeholder="Access Token / API Key" value={form.access_token||""} onChange={e=>setForm({...form,access_token:e.target.value})}/><input placeholder="Public Key" value={form.public_key||""} onChange={e=>setForm({...form,public_key:e.target.value})}/><input placeholder="Webhook Secret" value={form.webhook_secret||""} onChange={e=>setForm({...form,webhook_secret:e.target.value})}/><input placeholder="Chave Pix" value={form.pix_key||""} onChange={e=>setForm({...form,pix_key:e.target.value})}/><input placeholder="URL sucesso" value={form.success_url||""} onChange={e=>setForm({...form,success_url:e.target.value})}/><input placeholder="URL falha" value={form.failure_url||""} onChange={e=>setForm({...form,failure_url:e.target.value})}/><input placeholder="URL webhook" value={form.notification_url||""} onChange={e=>setForm({...form,notification_url:e.target.value})}/><label className="flex gap-2"><input type="checkbox" checked={!!form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Ativo</label><label className="flex gap-2"><input type="checkbox" checked={!!form.sandbox} onChange={e=>setForm({...form,sandbox:e.target.checked})}/>Sandbox</label><input placeholder="Instruções" value={form.instructions||""} onChange={e=>setForm({...form,instructions:e.target.value})}/><div className="flex gap-2 md:col-span-3"><button className="btn-primary" onClick={save}>{id?"Salvar edição":"Adicionar"}</button><button className="btn-danger" onClick={remove}>Excluir</button><button className="btn-secondary" onClick={()=>{setId("");setForm(empty)}}>Limpar</button></div>{msg&&<p className="text-yellow-300 md:col-span-3">{msg}</p>}</section>
    <section className="card p-4"><h2 className="font-bold mb-3">Configurações cadastradas</h2>{rows.length===0&&<p className="text-zinc-400">Nenhuma configuração.</p>}{rows.map(r=><div key={r.id} onClick={()=>{setId(r.id);setForm({...empty,...r})}} className="p-3 border-b border-zinc-800 cursor-pointer hover:bg-zinc-800 rounded-xl"><b>{r.display_name||r.provider}</b> · {r.provider} · {r.active?"Ativo":"Inativo"} · {r.sandbox?"Sandbox":"Produção"}</div>)}</section></div>
}
