"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { getSession } from "@/lib/session";
const empty:any={environment:"homologation",uf:"",csc_id:"",csc_token:"",certificate_url:"",certificate_password:"",provider:"manual",api_token:"",active:false};
export default function FiscalSettingsPage(){
 const[session,setSession]=useState<any>(null);const[rows,setRows]=useState<any[]>([]);const[form,setForm]=useState<any>(empty);const[id,setId]=useState("");const[msg,setMsg]=useState("");
 useEffect(()=>{const s=getSession();if(!s){location.href="/login";return;}if(!(s.master_admin||s.company_admin||s.role==="Administrador")){location.href="/dashboard";return;}setSession(s);load(s.company_id)},[]);
 async function load(cid=session?.company_id){if(!cid)return;const{data}=await supabase.from("fiscal_settings").select("*").eq("company_id",cid);setRows(data||[])}
 async function save(){if(!session)return;const payload={...form,company_id:session.company_id,updated_at:new Date().toISOString()};const r=id?await supabase.from("fiscal_settings").update(payload).eq("id",id):await supabase.from("fiscal_settings").insert(payload);if(r.error)return setMsg(r.error.message);setMsg("Configuração fiscal salva.");setId("");setForm(empty);load()}
 return <div className="space-y-6"><h1 className="text-3xl font-black">Configuração NFC-e</h1><p className="text-zinc-400">Estrutura para provedor fiscal, CSC e certificado. Emissão real exige API fiscal homologada.</p><section className="card p-4 grid md:grid-cols-3 gap-3"><select value={form.environment} onChange={e=>setForm({...form,environment:e.target.value})}><option value="homologation">Homologação</option><option value="production">Produção</option></select><input placeholder="UF" value={form.uf} onChange={e=>setForm({...form,uf:e.target.value})}/><input placeholder="CSC ID" value={form.csc_id} onChange={e=>setForm({...form,csc_id:e.target.value})}/><input placeholder="CSC Token" value={form.csc_token} onChange={e=>setForm({...form,csc_token:e.target.value})}/><input placeholder="URL certificado" value={form.certificate_url} onChange={e=>setForm({...form,certificate_url:e.target.value})}/><input placeholder="Senha certificado" value={form.certificate_password} onChange={e=>setForm({...form,certificate_password:e.target.value})}/><input placeholder="Provedor fiscal" value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})}/><input placeholder="API Token" value={form.api_token} onChange={e=>setForm({...form,api_token:e.target.value})}/><label className="flex gap-2"><input type="checkbox" checked={!!form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Ativo</label><button className="btn-primary" onClick={save}>Salvar</button>{msg&&<p className="text-yellow-300 md:col-span-3">{msg}</p>}</section><section className="card p-4">{rows.map(r=><div key={r.id} onClick={()=>{setId(r.id);setForm({...empty,...r})}} className="p-3 border-b border-zinc-800 cursor-pointer">{r.provider} · {r.environment} · {r.active?"Ativo":"Inativo"}</div>)}</section></div>
}
