"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { getSession } from "@/lib/session";
const empty:any={from_branch_id:"",to_branch_id:"",item_id:"",quantity:1,notes:"",status:"pending"};
export default function StockTransfersPage(){
 const[session,setSession]=useState<any>(null);const[rows,setRows]=useState<any[]>([]);const[branches,setBranches]=useState<any[]>([]);const[items,setItems]=useState<any[]>([]);const[form,setForm]=useState<any>(empty);const[msg,setMsg]=useState("");
 useEffect(()=>{const s=getSession();if(!s){location.href="/login";return;}setSession(s);load(s.company_id)},[]);
 async function load(cid=session?.company_id){if(!cid)return;const[{data:t},{data:b},{data:i}]=await Promise.all([supabase.from("stock_transfers").select("*").eq("company_id",cid).order("created_at",{ascending:false}),supabase.from("company_branches").select("*").eq("company_id",cid),supabase.from("stock_items").select("*").eq("company_id",cid)]);setRows(t||[]);setBranches(b||[]);setItems(i||[])}
 async function create(){if(!session)return;if(!form.item_id)return setMsg("Selecione item.");const{error}=await supabase.from("stock_transfers").insert({...form,company_id:session.company_id,requested_by:session.user_id});if(error)return setMsg(error.message);setMsg("Transferência criada.");setForm(empty);load()}
 async function approve(r:any){const{error}=await supabase.from("stock_transfers").update({status:"approved",approved_by:session.user_id,approved_at:new Date().toISOString()}).eq("id",r.id);if(error)return setMsg(error.message);setMsg("Aprovada.");load()}
 const branchName=(id:string)=>branches.find(b=>b.id===id)?.name||"-"; const itemName=(id:string)=>items.find(i=>i.id===id)?.name||"-";
 return <div className="space-y-6"><h1 className="text-3xl font-black">Transferência de Estoque</h1><section className="card p-4 grid md:grid-cols-3 gap-3"><select value={form.from_branch_id} onChange={e=>setForm({...form,from_branch_id:e.target.value})}><option value="">Origem</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select value={form.to_branch_id} onChange={e=>setForm({...form,to_branch_id:e.target.value})}><option value="">Destino</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select value={form.item_id} onChange={e=>setForm({...form,item_id:e.target.value})}><option value="">Item</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select><input type="number" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/><input placeholder="Observações" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button className="btn-primary" onClick={create}>Criar transferência</button>{msg&&<p className="text-yellow-300 md:col-span-3">{msg}</p>}</section><section className="card p-4 overflow-x-auto"><table className="w-full"><thead><tr className="text-left text-zinc-400"><th>Item</th><th>Origem</th><th>Destino</th><th>Qtd</th><th>Status</th><th>Ação</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b border-zinc-800"><td className="p-2">{itemName(r.item_id)}</td><td>{branchName(r.from_branch_id)}</td><td>{branchName(r.to_branch_id)}</td><td>{r.quantity}</td><td>{r.status}</td><td>{r.status==="pending"&&<button className="btn-secondary" onClick={()=>approve(r)}>Aprovar</button>}</td></tr>)}</tbody></table></section></div>
}
