"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { getSession } from "@/lib/session";
const wEmpty:any={provider:"manual",instance_id:"",api_url:"",api_key:"",phone_number:"",active:false};
const pEmpty:any={firebase_project_id:"",firebase_server_key:"",vapid_key:"",active:false};
export default function CommunicationSettingsPage(){
 const[session,setSession]=useState<any>(null);const[w,setW]=useState<any>(wEmpty);const[p,setP]=useState<any>(pEmpty);const[msg,setMsg]=useState("");
 useEffect(()=>{const s=getSession();if(!s){location.href="/login";return;}if(!(s.master_admin||s.company_admin||s.role==="Administrador")){location.href="/dashboard";return;}setSession(s);load(s.company_id)},[]);
 async function load(cid:string){const[{data:ws},{data:ps}]=await Promise.all([supabase.from("whatsapp_settings").select("*").eq("company_id",cid).limit(1).single(),supabase.from("push_settings").select("*").eq("company_id",cid).limit(1).single()]);if(ws)setW({...wEmpty,...ws});if(ps)setP({...pEmpty,...ps})}
 async function saveW(){if(!session)return;const payload={...w,company_id:session.company_id,updated_at:new Date().toISOString()};const r=w.id?await supabase.from("whatsapp_settings").update(payload).eq("id",w.id):await supabase.from("whatsapp_settings").insert(payload);if(r.error)return setMsg(r.error.message);setMsg("WhatsApp salvo.");load(session.company_id)}
 async function saveP(){if(!session)return;const payload={...p,company_id:session.company_id,updated_at:new Date().toISOString()};const r=p.id?await supabase.from("push_settings").update(payload).eq("id",p.id):await supabase.from("push_settings").insert(payload);if(r.error)return setMsg(r.error.message);setMsg("Push salvo.");load(session.company_id)}
 return <div className="space-y-6"><h1 className="text-3xl font-black">Comunicação</h1><section className="card p-4 grid md:grid-cols-3 gap-3"><h2 className="font-bold md:col-span-3">WhatsApp API</h2><input placeholder="Provedor" value={w.provider} onChange={e=>setW({...w,provider:e.target.value})}/><input placeholder="Instance ID" value={w.instance_id} onChange={e=>setW({...w,instance_id:e.target.value})}/><input placeholder="API URL" value={w.api_url} onChange={e=>setW({...w,api_url:e.target.value})}/><input placeholder="API Key" value={w.api_key} onChange={e=>setW({...w,api_key:e.target.value})}/><input placeholder="Número" value={w.phone_number} onChange={e=>setW({...w,phone_number:e.target.value})}/><label className="flex gap-2"><input type="checkbox" checked={!!w.active} onChange={e=>setW({...w,active:e.target.checked})}/>Ativo</label><button className="btn-primary" onClick={saveW}>Salvar WhatsApp</button></section><section className="card p-4 grid md:grid-cols-3 gap-3"><h2 className="font-bold md:col-span-3">Push Firebase</h2><input placeholder="Firebase Project ID" value={p.firebase_project_id} onChange={e=>setP({...p,firebase_project_id:e.target.value})}/><input placeholder="Firebase Server Key" value={p.firebase_server_key} onChange={e=>setP({...p,firebase_server_key:e.target.value})}/><input placeholder="VAPID Key" value={p.vapid_key} onChange={e=>setP({...p,vapid_key:e.target.value})}/><label className="flex gap-2"><input type="checkbox" checked={!!p.active} onChange={e=>setP({...p,active:e.target.checked})}/>Ativo</label><button className="btn-primary" onClick={saveP}>Salvar Push</button>{msg&&<p className="text-yellow-300 md:col-span-3">{msg}</p>}</section></div>
}
